name: CI Pipeline
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Dar permisos de ejecución #no está
      run: chmod +x mvnw
    - name: Build with Maven
      run: mvnw compile --batch-mode
    - name: Run tests
      run: mvnw verify ---batch-mode #usar verify para integracion, test solo unitarias
    - name: Generate reports #neesario?
      run: mvnw jacoco:report

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: target/site/jacoco #surefire-reports/

    - name: Generar Informe de Resultados
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Reporte de Pruebas JUnit
          path: 'target/*-reports/*.xml'
          reporter: java-junit

    - name: Upload JAR artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: app-jar
        path: target/*.jar
