name: Java CI/CD Hospital

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  # 1. FASE DE COMPILACIÓN
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: 'temurin', java-version: '21', cache: 'maven' }
      - run: chmod +x mvnw
      # Compilamos según el enunciado
      - run: ./mvnw compile --no-transfer-progress

  # 2. FASE DE TESTEO
  test:
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: 'temurin', java-version: '21', cache: 'maven' }
      - run: chmod +x mvnw
      # Ejecutamos las pruebas de integración
      - run: ./mvnw verify --no-transfer-progress

      # Generamos el reporte visual en GitHub
      - name: Generar Informe de Resultados
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Reporte de Pruebas JUnit
          path: 'target/*-reports/*.xml'
          reporter: java-junit

      # Guardamos el resultado de JaCoCo como artefacto
      - name: Artefacto de Cobertura Jacoco
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/

  # 3. FASE DE EMPAQUETADO
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: 'temurin', java-version: '21', cache: 'maven' }
      - run: chmod +x mvnw
      - run: ./mvnw -B clean package -DskipTests

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: hospital-jar
          path: target/*.jar
          retention-days: 1
